# Generated by Django 2.1.3 on 2019-01-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='博文标题')),
                ('article_type', models.IntegerField(choices=[(1, 'Python'), (2, 'Java'), (3, 'HTML'), (4, 'CSS'), (5, 'Jquery'), (6, 'Jquery'), (7, 'others')], default=None)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=32, verbose_name='标签名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phonenumber', models.IntegerField(unique=True, verbose_name='手机号码')),
                ('nikename', models.CharField(max_length=32, verbose_name='昵称')),
                ('avatar', models.ImageField(upload_to='', verbose_name='头像')),
                ('create_tiem', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
