# Generated by Django 2.1.3 on 2019-01-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('articletype', models.CharField(max_length=32, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32, verbose_name='分类')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.AddField(
            model_name='article',
            name='articletype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HOME.ArticleType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HOME.Category'),
            preserve_default=False,
        ),
    ]
