# Generated by Django 2.1.3 on 2018-12-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
    ]
