# Generated by Django 2.1.3 on 2018-12-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CDM', '0002_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='usergroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDM.usergroup'),
        ),
    ]
