# Generated by Django 2.1.3 on 2018-12-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CDM', '0003_auto_20181216_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDM.Usergroup'),
        ),
    ]
