# Generated by Django 2.1.3 on 2018-12-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181227_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_app',
            new_name='user2app',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserType'),
            preserve_default=False,
        ),
    ]
