# Generated by Django 2.1.3 on 2018-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0002_business_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='code',
            field=models.CharField(default='root', max_length=32, null=True),
        ),
    ]
