# Generated by Django 2.1.3 on 2018-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0003_auto_20181126_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(max_length=16),
        ),
    ]
