# Generated by Django 2.1.3 on 2018-11-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0004_auto_20181126_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostToApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.Application')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='hosttoapp',
            name='hid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.Host'),
        ),
    ]
