# Generated by Django 2.1.3 on 2018-11-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0005_auto_20181128_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='hid',
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
