# Generated by Django 2.1.3 on 2018-11-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0006_auto_20181128_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='r',
            field=models.ManyToManyField(to='app001.Host'),
        ),
    ]
