# Generated by Django 2.1.3 on 2018-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(db_column='省份', max_length=32)),
                ('create_time', models.TimeField(auto_now=True)),
                ('update_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
