# Generated by Django 2.1.3 on 2018-11-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='email',
            field=models.EmailField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
