# Generated by Django 2.1.3 on 2018-11-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181124_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='email',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=16, null=True),
        ),
    ]
