# Generated by Django 2.1.3 on 2018-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20181124_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='caption',
            field=models.CharField(db_column='用户组', max_length=32),
        ),
    ]
