# Generated by Django 2.1.3 on 2018-11-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_userinfo_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='caption',
            field=models.CharField(db_column='用户组', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
